"""cahnge name

Revision ID: 018d541e6fa4
Revises: 50c2aa47aa04
Create Date: 2026-07-09 11:37:13.857029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018d541e6fa4'
down_revision: Union[str, Sequence[str], None] = '50c2aa47aa04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('role', 'discription')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('discription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('role', 'description')
    # ### end Alembic commands ###
