"""initial_clean_schema

Revision ID: 0dd89ecbdbc2
Revises: 
Create Date: 2026-08-20 20:48:39.827395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dd89ecbdbc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('thumbnail_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'media', ['thumbnail_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'thumbnail')
    op.drop_constraint(op.f('research_authors_member_id_fkey'), 'research_authors', type_='foreignkey')
    op.create_foreign_key(None, 'research_authors', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'user_name',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'user_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'research_authors', type_='foreignkey')
    op.create_foreign_key(op.f('research_authors_member_id_fkey'), 'research_authors', 'members', ['member_id'], ['id'], onupdate='CASCADE')
    op.add_column('projects', sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'thumbnail_id')
    # ### end Alembic commands ###
