"""alter user tables

Revision ID: 2600215c7209
Revises: ad50a35576d6
Create Date: 2026-08-04 08:12:37.454845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2600215c7209'
down_revision: Union[str, Sequence[str], None] = 'ad50a35576d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_constraint(op.f('sub_groups_lead_id_fkey'), 'sub_groups', type_='foreignkey')
    op.create_foreign_key(None, 'sub_groups', 'users', ['lead_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('userrole_user_id_fkey'), 'userrole', type_='foreignkey')
    op.create_foreign_key(None, 'userrole', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userrole', type_='foreignkey')
    op.create_foreign_key(op.f('userrole_user_id_fkey'), 'userrole', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'sub_groups', type_='foreignkey')
    op.create_foreign_key(op.f('sub_groups_lead_id_fkey'), 'sub_groups', 'users', ['lead_id'], ['id'])
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subgroup_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=25), autoincrement=False, nullable=True),
    sa.Column('github', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linkedin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('portfolio', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('show_profile', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('joined_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subgroup_id'], ['sub_groups.id'], name=op.f('members_subgroup_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('members_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('members_pkey'))
    )
    # ### end Alembic commands ###
