"""finish table

Revision ID: 2c5f8dbf5d41
Revises: 46d4651f8838
Create Date: 2026-08-26 18:38:24.379461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5f8dbf5d41'
down_revision: Union[str, Sequence[str], None] = '46d4651f8838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('name', sa.String(length=30), nullable=True))
    op.add_column('contact', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('contact', sa.Column('subject', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('message', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('status', sa.String(), nullable=True))
    op.add_column('contact', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'created_at')
    op.drop_column('contact', 'status')
    op.drop_column('contact', 'message')
    op.drop_column('contact', 'subject')
    op.drop_column('contact', 'email')
    op.drop_column('contact', 'name')
    # ### end Alembic commands ###
