"""adding update time

Revision ID: 311f2ce2cf23
Revises: 018d541e6fa4
Create Date: 2026-08-02 14:54:08.434899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311f2ce2cf23'
down_revision: Union[str, Sequence[str], None] = '018d541e6fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_groups', sa.Column('upadated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_groups', 'upadated_at')
    # ### end Alembic commands ###
