"""adding gitcolumn

Revision ID: 3db08bacbe7a
Revises: 5c8ce2540bc1
Create Date: 2026-07-07 05:54:24.931629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db08bacbe7a'
down_revision: Union[str, Sequence[str], None] = '5c8ce2540bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'github_link')
    # ### end Alembic commands ###
