"""alter cover image column

Revision ID: 4ba58b191dc0
Revises: 275d2eddf738
Create Date: 2026-08-12 07:00:41.685494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ba58b191dc0'
down_revision: Union[str, Sequence[str], None] = '275d2eddf738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

   
   
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_table('projects')
    op.add_column('events', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'media', ['cover_image_id'], ['id'])
    op.drop_column('events', 'cover_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('cover_image', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'cover_image_id')
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repository_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('demo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technology_stack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('projects_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('research_authors',
    sa.Column('research_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('research_authors_member_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_id'], ['research.id'], name=op.f('research_authors_research_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('research_id', 'member_id', name=op.f('research_authors_pkey'))
    )
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('subgroup_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('file_url IS NOT NULL OR external_url IS NOT NULL', name=op.f('check_file_or_external_url')),
    sa.ForeignKeyConstraint(['subgroup_id'], ['sub_groups.id'], name=op.f('resources_subgroup_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('resources_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resources_pkey'))
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('research',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('abstract', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('publication_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('research_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('research_pkey'))
    )
    op.create_index(op.f('ix_research_slug'), 'research', ['slug'], unique=True)
    op.create_index(op.f('ix_research_id'), 'research', ['id'], unique=False)
    # ### end Alembic commands ###
