"""adding date func

Revision ID: 50c2aa47aa04
Revises: 3db08bacbe7a
Create Date: 2026-07-07 16:42:33.250320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50c2aa47aa04'
down_revision: Union[str, Sequence[str], None] = '3db08bacbe7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               # Added the explicit Postgres cast strategy here:
               postgresql_using="(CASE WHEN created_at = '' THEN NULL ELSE created_at::timestamp with time zone END)")
    
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               # Added the explicit cast back to text here just in case you ever roll back:
               postgresql_using="created_at::text")
    # ### end Alembic commands ###