"""adding test

Revision ID: 5c8ce2540bc1
Revises: e48e95b92bba
Create Date: 2026-07-05 10:39:37.785673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8ce2540bc1'
down_revision: Union[str, Sequence[str], None] = 'e48e95b92bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'test')
    # ### end Alembic commands ###
