"""creating resource models

Revision ID: 5e2cfffde8ba
Revises: ad50a35576d6
Create Date: 2026-08-05 11:14:49.180940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2cfffde8ba'
down_revision: Union[str, Sequence[str], None] = 'ad50a35576d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('title', sa.String(length=100), nullable=False))
    op.drop_column('resources', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('name', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('resources', 'title')
    # ### end Alembic commands ###
