"""add foregn key to user

Revision ID: 64ec8613ada1
Revises: 84028de40fbb
Create Date: 2026-08-07 14:43:48.940677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64ec8613ada1'
down_revision: Union[str, Sequence[str], None] = '84028de40fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_table('projects')
    op.alter_column('media', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'media', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.alter_column('media', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repository_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('demo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technology_stack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('projects_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('event_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('registration_link', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('published', 'draft', name='eventstatus'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('events_created_by_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('events_pkey'))
    )
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    # ### end Alembic commands ###
