"""alter table

Revision ID: 82c9afdeda98
Revises: 5c5c7a675812
Create Date: 2026-08-21 20:03:45.999371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c9afdeda98'
down_revision: Union[str, Sequence[str], None] = '5c5c7a675812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'registration_number',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               postgresql_using='registration_number::integer',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'registration_number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
