"""blog storage

Revision ID: 89046c67f9e9
Revises: 4ba58b191dc0
Create Date: 2026-08-12 23:47:07.668743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89046c67f9e9'
down_revision: Union[str, Sequence[str], None] = '4ba58b191dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_table('projects')
    op.add_column('blog_posts', sa.Column('featured_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog_posts', 'media', ['featured_image_id'], ['id'])
    op.drop_column('blog_posts', 'featured_image')
    op.add_column('events', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'events', 'media', ['cover_image_id'], ['id'])
    op.drop_column('events', 'cover_image')
    op.add_column('sub_groups', sa.Column('icon_id', sa.Integer(), nullable=True))
    op.add_column('sub_groups', sa.Column('cover_page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sub_groups', 'media', ['cover_page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sub_groups', 'media', ['icon_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sub_groups', 'icon')
    op.drop_column('sub_groups', 'cover_page')
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'media', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'avatar_id')
    op.add_column('sub_groups', sa.Column('cover_page', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sub_groups', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sub_groups', type_='foreignkey')
    op.drop_constraint(None, 'sub_groups', type_='foreignkey')
    op.drop_column('sub_groups', 'cover_page_id')
    op.drop_column('sub_groups', 'icon_id')
    op.add_column('events', sa.Column('cover_image', sa.VARCHAR(length=225), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'cover_image_id')
    op.add_column('blog_posts', sa.Column('featured_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.drop_column('blog_posts', 'featured_image_id')
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('repository_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('demo_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('technology_stack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('projects_created_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subgroup_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subgroup_id'], ['sub_groups.id'], name=op.f('resources_subgroup_id_fkey')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('resources_uploaded_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'subgroup_id', 'uploaded_by', name=op.f('resources_pkey'))
    )
    # ### end Alembic commands ###
