"""added new table

Revision ID: 9e61a5e05432
Revises: 35c339822af3
Create Date: 2026-08-28 18:21:52.841983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e61a5e05432'
down_revision: Union[str, Sequence[str], None] = '35c339822af3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_thumbnail_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'media', ['thumbnail_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('sub_groups_icon_id_fkey'), 'sub_groups', type_='foreignkey')
    op.drop_constraint(op.f('sub_groups_cover_page_id_fkey'), 'sub_groups', type_='foreignkey')
    op.create_foreign_key(None, 'sub_groups', 'media', ['icon_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sub_groups', 'media', ['cover_page_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_users_avatar_id_media'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'media', ['avatar_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_avatar_id_media'), 'users', 'media', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'sub_groups', type_='foreignkey')
    op.drop_constraint(None, 'sub_groups', type_='foreignkey')
    op.create_foreign_key(op.f('sub_groups_cover_page_id_fkey'), 'sub_groups', 'media', ['cover_page_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('sub_groups_icon_id_fkey'), 'sub_groups', 'media', ['icon_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_thumbnail_id_fkey'), 'projects', 'media', ['thumbnail_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
