"""Add centralized media for resource and research

Revision ID: c82edcfef114
Revises: 12a3f46a3ff8
Create Date: 2026-08-22 16:42:17.874021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82edcfef114'
down_revision: Union[str, Sequence[str], None] = '12a3f46a3ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('researchs', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'researchs', 'media', ['file_id'], ['id'])
    op.drop_column('researchs', 'pdf_url')
    op.add_column('resources', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resources', 'media', ['file_id'], ['id'])
    op.drop_constraint(op.f('check_file_or_external_url'), 'resources', type_='check')
    op.create_check_constraint('check_file_id_or_external_url', 'resources', 'file_id IS NOT NULL OR external_url IS NOT NULL')
    op.drop_column('resources', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint('check_file_id_or_external_url', 'resources', type_='check')
    op.create_check_constraint(op.f('check_file_or_external_url'), 'resources', 'file_url IS NOT NULL OR external_url IS NOT NULL')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'file_id')
    op.add_column('researchs', sa.Column('pdf_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'researchs', type_='foreignkey')
    op.drop_column('researchs', 'file_id')
    # ### end Alembic commands ###
