"""create blog post tables

Revision ID: cd132fcbf14d
Revises: 3b7e9f726c1e
Create Date: 2026-08-04 13:24:53.756316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd132fcbf14d'
down_revision: Union[str, Sequence[str], None] = '3b7e9f726c1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', name='poststatus'), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_blog_posts_excerpt'), 'blog_posts', ['excerpt'], unique=False)
    op.create_table('blog_categories',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('Category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'Category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_categories')
    op.drop_index(op.f('ix_blog_posts_excerpt'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_table('categories')
    # ### end Alembic commands ###
