"""alter events

Revision ID: cf2d1db1e8b9
Revises: 2600215c7209
Create Date: 2026-08-05 10:52:46.162368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf2d1db1e8b9'
down_revision: Union[str, Sequence[str], None] = '2600215c7209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop tables in correct dependency order (children first, parents last)
    op.drop_table('blog_categories')
    op.drop_index(op.f('ix_blog_posts_excerpt'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_table('categories')

    # 2. Add published_at column
    op.add_column('events', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # 3. Alter existing columns with explicit type casting for Postgres
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
               
    op.alter_column('events', 'event_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               postgresql_using="event_date::date",
               nullable=False)
               
    # Create the enum type before altering column to use it
    event_status_enum = postgresql.ENUM('published', 'draft', name='eventstatus')
    event_status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('events', 'status',
               existing_type=sa.VARCHAR(),
               type_=event_status_enum,
               postgresql_using="status::eventstatus",
               nullable=False)
               
    # 4. Create indexes
    op.create_index(op.f('ix_events_created_by'), 'events', ['created_by'], unique=False)
    op.create_index(op.f('ix_events_event_date'), 'events', ['event_date'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_event_date'), table_name='events')
    op.drop_index(op.f('ix_events_created_by'), table_name='events')
    
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('published', 'draft', name='eventstatus'),
               type_=sa.VARCHAR(),
               nullable=True)
               
    # Drop enum type on downgrade
    event_status_enum = postgresql.ENUM('published', 'draft', name='eventstatus')
    event_status_enum.drop(op.get_bind(), checkfirst=True)

    op.alter_column('events', 'event_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               nullable=True)
               
    op.alter_column('events', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
               
    op.drop_column('events', 'published_at')
    
    # Recreate tables in parent-first, child-second order
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', name=op.f('categories_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    
    op.create_table('blog_posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('featured_image', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'published', name='poststatus'), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('blog_posts_author_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('blog_posts_pkey')),
    sa.UniqueConstraint('slug', name=op.f('blog_posts_slug_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_blog_posts_excerpt'), 'blog_posts', ['excerpt'], unique=False)

    op.create_table('blog_categories',
    sa.Column('blog_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['Category_id'], ['categories.id'], name=op.f('blog_categories_Category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_id'], ['blog_posts.id'], name=op.f('blog_categories_blog_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id', 'Category_id', name=op.f('blog_categories_pkey'))
    )
    # ### end Alembic commands ###