"""fix tables

Revision ID: d78a93083b02
Revises: 9e61a5e05432
Create Date: 2026-08-28 18:56:23.953319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78a93083b02'
down_revision: Union[str, Sequence[str], None] = '9e61a5e05432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_posts_featured_image_id_fkey'), 'blog_posts', type_='foreignkey')
    op.create_foreign_key(None, 'blog_posts', 'media', ['featured_image_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('events_cover_image_id_fkey'), 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'media', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('members_subgroup_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'sub_groups', ['subgroup_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('researchs_file_id_fkey'), 'researchs', type_='foreignkey')
    op.drop_constraint(op.f('researchs_created_by_fkey'), 'researchs', type_='foreignkey')
    op.create_foreign_key(None, 'researchs', 'media', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'researchs', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resources_file_id_fkey'), 'resources', type_='foreignkey')
    op.drop_constraint(op.f('resources_subgroup_id_fkey'), 'resources', type_='foreignkey')
    op.drop_constraint(op.f('resources_uploaded_by_fkey'), 'resources', type_='foreignkey')
    op.create_foreign_key(None, 'resources', 'media', ['file_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'resources', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resources', 'sub_groups', ['subgroup_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('userrole_role_id_fkey'), 'userrole', type_='foreignkey')
    op.create_foreign_key(None, 'userrole', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userrole', type_='foreignkey')
    op.create_foreign_key(op.f('userrole_role_id_fkey'), 'userrole', 'role', ['role_id'], ['id'])
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.create_foreign_key(op.f('resources_uploaded_by_fkey'), 'resources', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(op.f('resources_subgroup_id_fkey'), 'resources', 'sub_groups', ['subgroup_id'], ['id'])
    op.create_foreign_key(op.f('resources_file_id_fkey'), 'resources', 'media', ['file_id'], ['id'])
    op.drop_constraint(None, 'researchs', type_='foreignkey')
    op.drop_constraint(None, 'researchs', type_='foreignkey')
    op.create_foreign_key(op.f('researchs_created_by_fkey'), 'researchs', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('researchs_file_id_fkey'), 'researchs', 'media', ['file_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'])
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_subgroup_id_fkey'), 'members', 'sub_groups', ['subgroup_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key(op.f('events_cover_image_id_fkey'), 'events', 'media', ['cover_image_id'], ['id'])
    op.drop_constraint(None, 'blog_posts', type_='foreignkey')
    op.create_foreign_key(op.f('blog_posts_featured_image_id_fkey'), 'blog_posts', 'media', ['featured_image_id'], ['id'])
    # ### end Alembic commands ###
